### ISSUE TITLE
Don't reset Rate Calculator window location?

### ISSUE THREAD

**Issue by SkarKorlan13** [raiguard/RecipeBook#122]
Just a quick suggestion: Currently the rate calculator window is movable and will stay where you put it while you are in a continuous play session, but if you save and exit and reenter the game, it resets the location to the center. If it could keep the location set by the player that would be great.

**Comment by raiguard** [comment]
I think you put this is the wrong repo :)

Anyway, the GUI will reset positions when mod configuration changes. This is true for all of my mods, because my mods remake the GUI from scratch when this happens. The newly released rate calculator 3.0 defaults to the top left of the screen, and you can reset it there by middle clicking the titlebar.

**Comment by SkarKorlan13** [comment]
FYI: in the mod portal page for rate calculator the link in the discussion section links to the recipe book GitHub issues section, that's why this is in the wrong repo. I only just noticed that.
Also it doesn't reset after mod configuration changes it's whenever you save and exit and then reopen that save
