### ISSUE TITLE
Mod crash on alt+click on landmine

### ISSUE THREAD

**Issue by SirRogro** [raiguard/RecipeBook#126]
Error message:
![image](https://github.com/raiguard/RecipeBook/assets/74187709/d061dc98-2f34-4d63-9b8d-4db4f95103ed)

To reproduce: 
Simply Alt+Click on Landmine in crafting section or assemler's output box (? Idk how to call. Where you can take item from assembler after assembling is done).

Save file: 
[_autosave3.zip](https://github.com/raiguard/RecipeBook/files/11634813/_autosave3.zip)

**Comment by raiguard** [comment]
I'm not able to reproduce. Did you make local changes to any mods without incrementing their version?

**Comment by SirRogro** [comment]
Nothing that would somehow influence landmine's item or recipe. In this [mod](https://mods.factorio.com/mod/k2-laser-artillery) I modified subgroup so it matches to Space Exploration vision of it (and Recipe Book works fine with it)

But anyway even with this modification by me still in use I cannot reproduce bug too. Lets say it was some uncaught script error and forget?

**Comment by raiguard** [comment]
That's what caused it. Doing _any_ changes without changing mod versions will break recipe book because it relies on cached prototypes to build the database on world load. That's one of the reasons why I am completely abandoning the current version and rewriting it from scratch. If you make local changes, you _must_ change a mod version to avoid RB crashing.
