### ISSUE TITLE
showing non researched recipes from mod

### ISSUE THREAD

**Issue by SGZ-Creations** [raiguard/RecipeBook#133]
Recipe book  All Mk 10 is missing except for the personal reactor.
![image](https://github.com/raiguard/RecipeBook/assets/59801736/9185b41d-c6f1-46bf-a30e-a67778403f85)

Selecting Filter
![image](https://github.com/raiguard/RecipeBook/assets/59801736/b849f1d1-668e-4ed5-9617-b6be6f777395)
 More than this I'm not sure what to show.

**Comment by SGZ-Creations** [comment]
Figured out a bit more. The part i don't get is that i haven't reserched more than Mk5 or 6 still 7-9 is saying to be reserched Still Mk10 is hidden behind your setting 

![image](https://github.com/raiguard/RecipeBook/assets/59801736/04d995f9-a4da-4036-a285-4f9316e62e20)
![image](https://github.com/raiguard/RecipeBook/assets/59801736/7110470b-053c-43f3-a8de-51b116a9cfec)

**Comment by raiguard** [comment]
Please attach your save file so I can take a look.

**Comment by SGZ-Creations** [comment]
![image](https://github.com/raiguard/RecipeBook/assets/59801736/c7cd23c9-9add-449e-9746-95eec025f43d)

**Comment by SGZ-Creations** [comment]
https://filetransfer.io/data-package/cJ1O3myu#link

**Comment by raiguard** [comment]
Thanks for the save file. This was a little tricky - the culprit is reverse factory's recycling recipes, which are hidden, but are all available at any point in the game. I have added exclusions for reverse factory to solve this issue.

![image](https://github.com/raiguard/RecipeBook/assets/3515394/3893f4cd-e548-411d-88ae-f09a0e64bad7)
