### ISSUE TITLE
Recipe Book Fatal Error on_load

### ISSUE THREAD

**Issue by Zancmok** [raiguard/RecipeBook#157]
Im trying to load a game and got a critical error from the Recipe Book mod, here is the error: 
The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_load()
__RecipeBook__/scripts/database/item.lua:17: attempt to index local 'group_data' (a nil value)
stack traceback:

    __RecipeBook__/scripts/database/item.lua:17: in function <__RecipeBook__/scripts/database/item.lua:7>
    (...tail calls...)
    __RecipeBook__/scripts/database.lua:69: in function 'build'
    __RecipeBook__/control.lua:196: in function <__RecipeBook__/control.lua:191>

The save previously had the mod and it stopped working trought the playtrough, removing and reading the mods seems to fix the issue

The original file that gives the error: 
[SpaceBlock[item=spaceblock-matter].zip](https://github.com/raiguard/RecipeBook/files/14470203/SpaceBlock.item.spaceblock-matter.zip)

**Comment by raiguard** [comment]
Did you change mod contents without changing mod versions?

**Comment by Zancmok** [comment]
> Did you change mod contents without changing mod versions?

yes

**Comment by raiguard** [comment]
That's why. RB3 caches a ton of stuff outside of the `global` table and re-builds it during map load. If you change mod contents without changing a mod's version then it will have no way to tell that a configuration change is going to occur and so it attempts to load potentially invalid data.

RB4 will not have this issue.
